version: '3'
services:
  backend:
    image: mcdgs/ads-g10-meipl-2021-back:latest
    container_name: backend
    restart: always
    ports:
      - '8080:8080'
    networks:
      - backend
  frontend:
    image: mcdgs/ads-g10-meipl-2021-front:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '8081:8080'
    networks:
      - backend
networks:
  backend:
