# This workflow will deploy frontend to heroku,

name: Frontend Deploy to Heroku

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run frontend tests
      uses: actions/setup-node@v2
    - run: npm install
      working-directory: frontend
    - run: npm run test
      working-directory: frontend

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [frontend-test]
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      - run: npm install express serve-static --save
        working-directory: frontend
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ads-g10-meipl-2021"
          heroku_email: "mcdgs@iscte-iul.pt"
          buildpack: "heroku/nodejs"
          appdir: "frontend"