# This workflow will deploy frontend to docker hub.

name: Frontend Deploy to Docker Hub

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run frontend tests
      uses: actions/setup-node@v2

    - run: npm install
      working-directory: frontend

    - run: npm run test
      working-directory: frontend

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: [frontend-test]
    steps:
      - uses: actions/checkout@v2

      - run: npm install
        working-directory: frontend

      - run: npm run build
        working-directory: frontend

      - run: npm install express serve-static --save
        working-directory: frontend

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ads-g10-meipl-2021-front:latest
        
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ads-g10-meipl-2021-front:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}