# This workflow will deploy backend to docker hub,

name: Backend Deploy to Docker Hub

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run backend tests
        working-directory: backend
        run: mvn test --file pom.xml

  backend-deploy:
    runs-on: ubuntu-latest
    needs: [backend-tests]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ads-g10-meipl-2021-back:latest
        
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ads-g10-meipl-2021-back:latest
          run: |
            echo "runing the docker image"
            echo "Testing the java app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}
